blog/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do  
    post 'api/v1/login', to: 'users/sessions#create'
    get 'api/v1/logout', to: 'users/sessions#destroy'  
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Defines the root path route ("/")
  root "articles#index"

  resources :articles do
    resources :comments
  end
  get '/admin', to: redirect('/admin/articles')
  namespace :admin do
    resources :articles do
      resources :comments
      get 'new', to: 'articles#new', as: 'new'
    end
    
    get 'articles/:id', to: 'articles#show', as: 'admin_article'
    get 'articles/:id/comments', to: 'comments#index', as: 'admin_article_comments'
    get 'articles/:id/generate_pdf', to: 'articles#generate_pdf', as: 'generate_pdf'   
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
end

blog/app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

blog/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ArticlesController
  before_action :authenticate_user!
  before_action :require_admin!

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to admin_article_path(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path, status: :see_other
  end

  def generate_pdf
    @article = Article.find(params[:id])
    @comments = @article.comments.order(:created_at)
    html = render_to_string(action: :show)
    pdf_generator = PdfGenerator.new(@article, @comments, html)
    file = pdf_generator.download
    send_file file, type: 'application/pdf', disposition: 'attachment'
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.paginate(page: params[:page], per_page: 10)
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<h1>New Article</h1>

<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

blog/app/views/articles/index.html.erb
<h1 class="mb-4">Articles</h1>
<h2 class="mb-4">Our blog has <span class="badge bg-primary"><%= Article.public_count %></span> articles and counting!</h2>
<ul class="list-group mb-4">
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <li class="list-group-item">
                <%= link_to article.title, article_path(article, authentication_token: params[:authentication_token]) %>
            </li>
        <% end %>
    <% end %>
</ul>
<%= will_paginate @articles, :class => 'pagination justify-content-center' %>
<%= render 'shared/sign' %>

blog/app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %></h1>

  <div class="row">
    <div class="col-md-8">
      <p><%= @article.body %></p>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <h2>Comments</h2>
        </div>
        <div class="card-body">
          <%= render @comments %>
          <%= will_paginate @comments %>
        </div>
      </div>
      <div class="card mt-3">
        <div class="card-header">
          <h2>Add a comment:</h2>
        </div>
        <div class="card-body">
          <%= render 'comments/form' %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/sign' %>
</div>

blog/app/views/articles/show.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= @article.title %></title>
    <%= wicked_pdf_stylesheet_link_tag 'pdf', media: 'all' %>
    <%= wicked_pdf_javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h1><%= @article.title %></h1>
    <p><%= @article.body %></p>
    <table>
      <thead>
        <tr>
          <th>Commenter</th>
          <th>Comment Body</th>
        </tr>
      </thead>
      <tbody>
        <% @article.comments.each do |comment| %>
          <tr>
            <td><%= comment.commenter %></td>
            <td><%= comment.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>