blog/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do  
    post 'api/v1/login', to: 'users/sessions#create'
    get 'api/v1/logout', to: 'users/sessions#destroy'  
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Defines the root path route ("/")
  root "articles#index"

  resources :articles do
    resources :comments
  end
  get '/admin', to: redirect('/admin/articles')
  namespace :admin do
    resources :articles do
      resources :comments
      get 'new', to: 'articles#new', as: 'new'
    end
    
    get 'articles/:id', to: 'articles#show', as: 'admin_article'
    get 'articles/:id/comments', to: 'comments#index', as: 'admin_article_comments'
    get 'articles/:id/generate_pdf', to: 'articles#generate_pdf', as: 'generate_pdf'   
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
end

blog/app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

blog/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ArticlesController
  before_action :authenticate_user!
  before_action :require_admin!

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to admin_article_path(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path, status: :see_other
  end

  def generate_pdf
    @article = Article.find(params[:id])
    @comments = @article.comments.order(:created_at)
    html = render_to_string(action: :show)
    pdf_generator = PdfGenerator.new(@article, @comments, html)
    file = pdf_generator.download
    send_file file, type: 'application/pdf', disposition: 'attachment'
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.paginate(page: params[:page], per_page: 10)
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/admin/articles/_form.html.erb
<%= form_for [:admin, article], html: { class: "form" } do |form| %>
  <div class="form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="invalid-feedback d-block"><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="invalid-feedback d-block"><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, ['public', 'private', 'archived'], { selected: 'public' }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

blog/app/views/admin/articles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1>Edit Article</h1>
        </div>
        <div class="card-body">
          <%= render "form", article: @article%>
        </div>
      </div>
    </div>
  </div>
</div>

blog/app/views/admin/articles/generate_pdf.pdf.erb
<!-- intentionally blank -->

blog/app/views/admin/articles/index.html.erb
<h1 class="mb-4">Articles</h1>
<h2>Our blog has <%= Article.public_count %> articles and counting!</h2>

<div class="list-group mb-4">
  <% @articles.each do |article| %>
    <a href="<%= admin_article_path(article) %>" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <%= article.title %>
      <% if article.archived?  %>
        <span class="badge badge-danger badge-pill">Archived</span>
      <% end %>
    </a>
  <% end %>
</div>

<%= will_paginate @articles, class: "pagination justify-content-center" %>

<%= link_to "New Article", new_admin_article_path, class: "btn btn-primary mb-4" %>

<%= render 'shared/sign' %>

blog/app/views/admin/articles/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1>New Article</h1>
        </div>
        <div class="card-body">
          <%= render "form", article: @article%>
        </div>
      </div>
    </div>
  </div>
</div>

blog/app/views/admin/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @article.title %></h1>

      <p><%= @article.body %></p>

      <%= link_to "Edit", edit_admin_article_path(@article), class: "btn btn-primary" %>
      <%= link_to "Destroy", admin_article_path(@article), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, method: :delete, class: "btn btn-danger" %>


      <div class="mt-5">
        <%= link_to "Generate PDF", admin_generate_pdf_path(format: :pdf), class: "btn btn-primary" %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <h2>Comments</h2>
        </div>
        <div class="card-body">
          <%= render @comments %>
          <%= will_paginate @comments %>
        </div>
      </div>
      
      <div class="card mt-3">
        <div class="card-header">
          <h2>Add a comment:</h2>
        </div>
        <div class="card-body">
          <%= render 'comments/form' %>
        </div>
      </div>
    </div>
  </div>

  <%= render 'shared/sign' %>
</div>